/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.danman85.file_encryptor;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.stage.Stage;
import nl.danman85.file_encryptor.client.Client;
import nl.danman85.file_encryptor.client.configuration.ConfigException;
import nl.danman85.file_encryptor.client.configuration.ConfigValidator;
import nl.danman85.file_encryptor.exception.ExceptionLoggingHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App extends Application {

    public static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        LOGGER.info("Starting Application");
        launch(args);
    }

    @Override
    public void start(final Stage stage) {

        validateConfig();
        startClient(stage);
    }

    private void validateConfig() {
        final var validator = new ConfigValidator();
        try {
            validator.validate();
        } catch (ConfigException e) {
            LOGGER.error("Configuration validation failed, exiting application");
            Platform.exit();
        }
    }

    private void startClient(final Stage stage) {
        var exceptionHandler = new ExceptionLoggingHandler();

        try {
            final var client = new Client();
            client.start(stage);
        } catch (final Exception e) {
            exceptionHandler.handle(e);
        }
    }
}
