/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.danman85;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {

    @Test
    void appTest() {
        assertTrue(true);
    }
}
